//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xiperware.WiretapAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xiperware.WiretapAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium
        ///1
        ///     0.4840000E+01     0.5069000E+02
        ///     0.5477649E+01     0.4949361E+02
        ///     0.5467231E+01     0.4950081E+02
        ///     0.5464556E+01     0.4950832E+02
        ///     0.5437978E+01     0.4951804E+02
        ///     0.5443867E+01     0.4952040E+02
        ///     0.5451906E+01     0.4952119E+02
        ///     0.5461178E+01     0.4952770E+02
        ///     0.5469846E+01     0.4953101E+02
        ///     0.5469151E+01     0.4953625E+02
        ///     0.5459969E+01     0.4954389E+02
        ///     0.5444859E+01     0.4955016E+02
        ///     0.5456327E+01     0.4956519E+02
        ///     0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string border_belgium {
            get {
                return ResourceManager.GetString("border_belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France
        ///42
        ///     0.3480000E+01     0.4981000E+02
        ///     0.2546947E+01     0.5109281E+02
        ///     0.2554190E+01     0.5108006E+02
        ///     0.2554190E+01     0.5108006E+02
        ///     0.2562225E+01     0.5106775E+02
        ///     0.2574418E+01     0.5102285E+02
        ///     0.2570873E+01     0.5101425E+02
        ///     0.2577935E+01     0.5100077E+02
        ///     0.2586647E+01     0.5099674E+02
        ///     0.2608061E+01     0.5099249E+02
        ///     0.2610502E+01     0.5098960E+02
        ///     0.2609269E+01     0.5098338E+02
        ///     0.2614596E+01     0.5097281E+02
        ///     0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string border_france {
            get {
                return ResourceManager.GetString("border_france", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany
        ///49
        ///     0.7400000E+01     0.5078000E+02
        ///     0.8020221E+01     0.4876530E+02
        ///     0.8023747E+01     0.4876847E+02
        ///     0.8029333E+01     0.4878531E+02
        ///     0.8036753E+01     0.4879231E+02
        ///     0.8041635E+01     0.4879432E+02
        ///     0.8049239E+01     0.4879469E+02
        ///     0.8060232E+01     0.4879251E+02
        ///     0.8067849E+01     0.4879334E+02
        ///     0.8077945E+01     0.4879665E+02
        ///     0.8090241E+01     0.4880497E+02
        ///     0.8100858E+01     0.4881490E+02
        ///     0.8108732E+01     0.4882555E+02
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string border_germany {
            get {
                return ResourceManager.GetString("border_germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg
        ///1
        ///     0.6163000E+01     0.4981000E+02
        ///     0.5967428E+01     0.5015868E+02
        ///     0.5964563E+01     0.5015981E+02
        ///     0.5962637E+01     0.5017207E+02
        ///     0.5974896E+01     0.5017703E+02
        ///     0.5996220E+01     0.5017719E+02
        ///     0.6020256E+01     0.5018468E+02
        ///     0.6025583E+01     0.5018495E+02
        ///     0.6029886E+01     0.5018293E+02
        ///     0.6032246E+01     0.5017014E+02
        ///     0.6037641E+01     0.5016652E+02
        ///     0.6055127E+01     0.5016230E+02
        ///     0.6062666E+01     0.5015778E+02
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string border_luxembourg {
            get {
                return ResourceManager.GetString("border_luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands
        ///13
        ///     0.5020000E+01     0.5200000E+02
        ///     0.7185874E+01     0.5294425E+02
        ///     0.7165218E+01     0.5292334E+02
        ///     0.7115944E+01     0.5287334E+02
        ///     0.7089423E+01     0.5285077E+02
        ///     0.7094264E+01     0.5283956E+02
        ///     0.7076054E+01     0.5281536E+02
        ///     0.7075584E+01     0.5281382E+02
        ///     0.7071462E+01     0.5280029E+02
        ///     0.7073296E+01     0.5279023E+02
        ///     0.7070054E+01     0.5274131E+02
        ///     0.7062733E+01     0.5268870E+02
        ///     0.7056458E+01     0.5264350E+02
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string border_netherlands {
            get {
                return ResourceManager.GetString("border_netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to England
        ///1
        ///     0.0200000E+01     0.5115000E+02
        ///.
        /// </summary>
        public static string border_uk {
            get {
                return ResourceManager.GetString("border_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap contested {
            get {
                object obj = ResourceManager.GetObject("contested", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_ao_placed {
            get {
                object obj = ResourceManager.GetObject("event_ao_placed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_ao_placed_small {
            get {
                object obj = ResourceManager.GetObject("event_ao_placed_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_ao_withdrawn {
            get {
                object obj = ResourceManager.GetObject("event_ao_withdrawn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_ao_withdrawn_small {
            get {
                object obj = ResourceManager.GetObject("event_ao_withdrawn_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_chokepointcapture_british {
            get {
                object obj = ResourceManager.GetObject("event_chokepointcapture_british", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_chokepointcapture_french {
            get {
                object obj = ResourceManager.GetObject("event_chokepointcapture_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_chokepointcapture_german {
            get {
                object obj = ResourceManager.GetObject("event_chokepointcapture_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_chokepointcapture_usa {
            get {
                object obj = ResourceManager.GetObject("event_chokepointcapture_usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_controlchanged {
            get {
                object obj = ResourceManager.GetObject("event_controlchanged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_controlchanged_british {
            get {
                object obj = ResourceManager.GetObject("event_controlchanged_british", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_controlchanged_french {
            get {
                object obj = ResourceManager.GetObject("event_controlchanged_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_controlchanged_german {
            get {
                object obj = ResourceManager.GetObject("event_controlchanged_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_controlchanged_usa {
            get {
                object obj = ResourceManager.GetObject("event_controlchanged_usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_facilitycapture_british {
            get {
                object obj = ResourceManager.GetObject("event_facilitycapture_british", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_facilitycapture_french {
            get {
                object obj = ResourceManager.GetObject("event_facilitycapture_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_facilitycapture_german {
            get {
                object obj = ResourceManager.GetObject("event_facilitycapture_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_facilitycapture_usa {
            get {
                object obj = ResourceManager.GetObject("event_facilitycapture_usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_factory_damaged {
            get {
                object obj = ResourceManager.GetObject("event_factory_damaged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_factory_destroyed {
            get {
                object obj = ResourceManager.GetObject("event_factory_destroyed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_factory_healthy {
            get {
                object obj = ResourceManager.GetObject("event_factory_healthy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_factory_rdpoff {
            get {
                object obj = ResourceManager.GetObject("event_factory_rdpoff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_factory_rdpon {
            get {
                object obj = ResourceManager.GetObject("event_factory_rdpon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_firebase_blown {
            get {
                object obj = ResourceManager.GetObject("event_firebase_blown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_deployed_british {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_deployed_british", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_deployed_french {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_deployed_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_deployed_german {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_deployed_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_deployed_usa {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_deployed_usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_moved_british {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_moved_british", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_moved_french {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_moved_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_moved_german {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_moved_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_moved_usa {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_moved_usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_routed_british {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_routed_british", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_routed_french {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_routed_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_routed_german {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_routed_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_hcunit_routed_usa {
            get {
                object obj = ResourceManager.GetObject("event_hcunit_routed_usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_regained {
            get {
                object obj = ResourceManager.GetObject("event_regained", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_regained_british {
            get {
                object obj = ResourceManager.GetObject("event_regained_british", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_regained_french {
            get {
                object obj = ResourceManager.GetObject("event_regained_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_regained_german {
            get {
                object obj = ResourceManager.GetObject("event_regained_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_regained_usa {
            get {
                object obj = ResourceManager.GetObject("event_regained_usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_spawnablecapture {
            get {
                object obj = ResourceManager.GetObject("event_spawnablecapture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_spawnablecapture_british {
            get {
                object obj = ResourceManager.GetObject("event_spawnablecapture_british", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_spawnablecapture_french {
            get {
                object obj = ResourceManager.GetObject("event_spawnablecapture_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_spawnablecapture_german {
            get {
                object obj = ResourceManager.GetObject("event_spawnablecapture_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_spawnablecapture_usa {
            get {
                object obj = ResourceManager.GetObject("event_spawnablecapture_usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_underattack {
            get {
                object obj = ResourceManager.GetObject("event_underattack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_underattack_british {
            get {
                object obj = ResourceManager.GetObject("event_underattack_british", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_underattack_french {
            get {
                object obj = ResourceManager.GetObject("event_underattack_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_underattack_german {
            get {
                object obj = ResourceManager.GetObject("event_underattack_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap event_underattack_usa {
            get {
                object obj = ResourceManager.GetObject("event_underattack_usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap facility_airbase {
            get {
                object obj = ResourceManager.GetObject("facility_airbase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap facility_armybase {
            get {
                object obj = ResourceManager.GetObject("facility_armybase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap facility_city {
            get {
                object obj = ResourceManager.GetObject("facility_city", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap facility_depot {
            get {
                object obj = ResourceManager.GetObject("facility_depot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap facility_factory {
            get {
                object obj = ResourceManager.GetObject("facility_factory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap facility_firebase {
            get {
                object obj = ResourceManager.GetObject("facility_firebase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap facility_navalbase {
            get {
                object obj = ResourceManager.GetObject("facility_navalbase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_brigade_british {
            get {
                object obj = ResourceManager.GetObject("flag_brigade_british", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_brigade_french {
            get {
                object obj = ResourceManager.GetObject("flag_brigade_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_brigade_german {
            get {
                object obj = ResourceManager.GetObject("flag_brigade_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_brigade_usa {
            get {
                object obj = ResourceManager.GetObject("flag_brigade_usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_country_british {
            get {
                object obj = ResourceManager.GetObject("flag_country_british", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_country_french {
            get {
                object obj = ResourceManager.GetObject("flag_country_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_country_german {
            get {
                object obj = ResourceManager.GetObject("flag_country_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_country_nf {
            get {
                object obj = ResourceManager.GetObject("flag_country_nf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_country_nh {
            get {
                object obj = ResourceManager.GetObject("flag_country_nh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_country_usa {
            get {
                object obj = ResourceManager.GetObject("flag_country_usa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ledgraph0 {
            get {
                object obj = ResourceManager.GetObject("ledgraph0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ledgraph1 {
            get {
                object obj = ResourceManager.GetObject("ledgraph1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ledgraph2 {
            get {
                object obj = ResourceManager.GetObject("ledgraph2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ledgraph3 {
            get {
                object obj = ResourceManager.GetObject("ledgraph3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ledgraph4 {
            get {
                object obj = ResourceManager.GetObject("ledgraph4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- Downloaded from http://ww2.kfs.org/ranklist.xml at Wed May 14 15:26:35 2008 --&gt;
        ///&lt;ranklist version=&quot;1.1&quot;&gt;
        ///	&lt;rank level=&quot;1&quot; type=&quot;enlisted&quot;&gt;
        ///		&lt;british country=&quot;1&quot;&gt;
        ///			&lt;ground branch=&quot;1&quot;&gt;Recruit&lt;/ground&gt;
        ///			&lt;air branch=&quot;2&quot;&gt;Aircraftsman&lt;/air&gt;
        ///			&lt;navy branch=&quot;3&quot;&gt;Recruit&lt;/navy&gt;
        ///		&lt;/british&gt;
        ///		&lt;french country=&quot;3&quot;&gt;
        ///			&lt;ground branch=&quot;1&quot;&gt;Recrue&lt;/ground&gt;
        ///			&lt;air branch=&quot;2&quot;&gt;Aviateur&lt;/air&gt;
        ///			&lt;navy branch=&quot;3&quot;&gt;Matelot&lt;/navy&gt;
        ///		&lt;/french&gt;
        ///		&lt;german country=&quot;4&quot;&gt;
        ///			&lt;ground branch [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ranklist {
            get {
                return ResourceManager.GetString("ranklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap spawnable {
            get {
                object obj = ResourceManager.GetObject("spawnable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
