//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEGM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Vehicles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vehicles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEGM.Vehicles", typeof(Vehicles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap vehicle001 {
            get {
                object obj = ResourceManager.GetObject("vehicle001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle002 {
            get {
                object obj = ResourceManager.GetObject("vehicle002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle004 {
            get {
                object obj = ResourceManager.GetObject("vehicle004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle006 {
            get {
                object obj = ResourceManager.GetObject("vehicle006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle007 {
            get {
                object obj = ResourceManager.GetObject("vehicle007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle008 {
            get {
                object obj = ResourceManager.GetObject("vehicle008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle009 {
            get {
                object obj = ResourceManager.GetObject("vehicle009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle010 {
            get {
                object obj = ResourceManager.GetObject("vehicle010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle011 {
            get {
                object obj = ResourceManager.GetObject("vehicle011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle014 {
            get {
                object obj = ResourceManager.GetObject("vehicle014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle015 {
            get {
                object obj = ResourceManager.GetObject("vehicle015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle017 {
            get {
                object obj = ResourceManager.GetObject("vehicle017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle018 {
            get {
                object obj = ResourceManager.GetObject("vehicle018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle019 {
            get {
                object obj = ResourceManager.GetObject("vehicle019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle020 {
            get {
                object obj = ResourceManager.GetObject("vehicle020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle021 {
            get {
                object obj = ResourceManager.GetObject("vehicle021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle022 {
            get {
                object obj = ResourceManager.GetObject("vehicle022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle023 {
            get {
                object obj = ResourceManager.GetObject("vehicle023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle024 {
            get {
                object obj = ResourceManager.GetObject("vehicle024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle025 {
            get {
                object obj = ResourceManager.GetObject("vehicle025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle026 {
            get {
                object obj = ResourceManager.GetObject("vehicle026", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle027 {
            get {
                object obj = ResourceManager.GetObject("vehicle027", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle028 {
            get {
                object obj = ResourceManager.GetObject("vehicle028", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle029 {
            get {
                object obj = ResourceManager.GetObject("vehicle029", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle030 {
            get {
                object obj = ResourceManager.GetObject("vehicle030", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle031 {
            get {
                object obj = ResourceManager.GetObject("vehicle031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle032 {
            get {
                object obj = ResourceManager.GetObject("vehicle032", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle033 {
            get {
                object obj = ResourceManager.GetObject("vehicle033", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle062 {
            get {
                object obj = ResourceManager.GetObject("vehicle062", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle063 {
            get {
                object obj = ResourceManager.GetObject("vehicle063", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle064 {
            get {
                object obj = ResourceManager.GetObject("vehicle064", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle065 {
            get {
                object obj = ResourceManager.GetObject("vehicle065", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle066 {
            get {
                object obj = ResourceManager.GetObject("vehicle066", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle067 {
            get {
                object obj = ResourceManager.GetObject("vehicle067", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle070 {
            get {
                object obj = ResourceManager.GetObject("vehicle070", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle071 {
            get {
                object obj = ResourceManager.GetObject("vehicle071", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle072 {
            get {
                object obj = ResourceManager.GetObject("vehicle072", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle073 {
            get {
                object obj = ResourceManager.GetObject("vehicle073", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle074 {
            get {
                object obj = ResourceManager.GetObject("vehicle074", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle075 {
            get {
                object obj = ResourceManager.GetObject("vehicle075", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle076 {
            get {
                object obj = ResourceManager.GetObject("vehicle076", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle077 {
            get {
                object obj = ResourceManager.GetObject("vehicle077", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle078 {
            get {
                object obj = ResourceManager.GetObject("vehicle078", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle079 {
            get {
                object obj = ResourceManager.GetObject("vehicle079", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle080 {
            get {
                object obj = ResourceManager.GetObject("vehicle080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle081 {
            get {
                object obj = ResourceManager.GetObject("vehicle081", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle082 {
            get {
                object obj = ResourceManager.GetObject("vehicle082", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle083 {
            get {
                object obj = ResourceManager.GetObject("vehicle083", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle084 {
            get {
                object obj = ResourceManager.GetObject("vehicle084", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle085 {
            get {
                object obj = ResourceManager.GetObject("vehicle085", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle086 {
            get {
                object obj = ResourceManager.GetObject("vehicle086", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle087 {
            get {
                object obj = ResourceManager.GetObject("vehicle087", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle088 {
            get {
                object obj = ResourceManager.GetObject("vehicle088", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle089 {
            get {
                object obj = ResourceManager.GetObject("vehicle089", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle090 {
            get {
                object obj = ResourceManager.GetObject("vehicle090", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle091 {
            get {
                object obj = ResourceManager.GetObject("vehicle091", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle092 {
            get {
                object obj = ResourceManager.GetObject("vehicle092", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle093 {
            get {
                object obj = ResourceManager.GetObject("vehicle093", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle094 {
            get {
                object obj = ResourceManager.GetObject("vehicle094", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle095 {
            get {
                object obj = ResourceManager.GetObject("vehicle095", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle096 {
            get {
                object obj = ResourceManager.GetObject("vehicle096", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle097 {
            get {
                object obj = ResourceManager.GetObject("vehicle097", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle098 {
            get {
                object obj = ResourceManager.GetObject("vehicle098", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle099 {
            get {
                object obj = ResourceManager.GetObject("vehicle099", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle100 {
            get {
                object obj = ResourceManager.GetObject("vehicle100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle101 {
            get {
                object obj = ResourceManager.GetObject("vehicle101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle102 {
            get {
                object obj = ResourceManager.GetObject("vehicle102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle103 {
            get {
                object obj = ResourceManager.GetObject("vehicle103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle104 {
            get {
                object obj = ResourceManager.GetObject("vehicle104", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle105 {
            get {
                object obj = ResourceManager.GetObject("vehicle105", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle106 {
            get {
                object obj = ResourceManager.GetObject("vehicle106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle107 {
            get {
                object obj = ResourceManager.GetObject("vehicle107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle108 {
            get {
                object obj = ResourceManager.GetObject("vehicle108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle109 {
            get {
                object obj = ResourceManager.GetObject("vehicle109", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle110 {
            get {
                object obj = ResourceManager.GetObject("vehicle110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle111 {
            get {
                object obj = ResourceManager.GetObject("vehicle111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle112 {
            get {
                object obj = ResourceManager.GetObject("vehicle112", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle113 {
            get {
                object obj = ResourceManager.GetObject("vehicle113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle114 {
            get {
                object obj = ResourceManager.GetObject("vehicle114", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle118 {
            get {
                object obj = ResourceManager.GetObject("vehicle118", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle119 {
            get {
                object obj = ResourceManager.GetObject("vehicle119", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle120 {
            get {
                object obj = ResourceManager.GetObject("vehicle120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle121 {
            get {
                object obj = ResourceManager.GetObject("vehicle121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle128 {
            get {
                object obj = ResourceManager.GetObject("vehicle128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle129 {
            get {
                object obj = ResourceManager.GetObject("vehicle129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle130 {
            get {
                object obj = ResourceManager.GetObject("vehicle130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle131 {
            get {
                object obj = ResourceManager.GetObject("vehicle131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle132 {
            get {
                object obj = ResourceManager.GetObject("vehicle132", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle133 {
            get {
                object obj = ResourceManager.GetObject("vehicle133", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle134 {
            get {
                object obj = ResourceManager.GetObject("vehicle134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle135 {
            get {
                object obj = ResourceManager.GetObject("vehicle135", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle136 {
            get {
                object obj = ResourceManager.GetObject("vehicle136", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle140 {
            get {
                object obj = ResourceManager.GetObject("vehicle140", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle141 {
            get {
                object obj = ResourceManager.GetObject("vehicle141", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle142 {
            get {
                object obj = ResourceManager.GetObject("vehicle142", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle146 {
            get {
                object obj = ResourceManager.GetObject("vehicle146", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle150 {
            get {
                object obj = ResourceManager.GetObject("vehicle150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle154 {
            get {
                object obj = ResourceManager.GetObject("vehicle154", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle159 {
            get {
                object obj = ResourceManager.GetObject("vehicle159", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle160 {
            get {
                object obj = ResourceManager.GetObject("vehicle160", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle161 {
            get {
                object obj = ResourceManager.GetObject("vehicle161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle162 {
            get {
                object obj = ResourceManager.GetObject("vehicle162", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle164 {
            get {
                object obj = ResourceManager.GetObject("vehicle164", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle165 {
            get {
                object obj = ResourceManager.GetObject("vehicle165", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle166 {
            get {
                object obj = ResourceManager.GetObject("vehicle166", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle167 {
            get {
                object obj = ResourceManager.GetObject("vehicle167", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle168 {
            get {
                object obj = ResourceManager.GetObject("vehicle168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle169 {
            get {
                object obj = ResourceManager.GetObject("vehicle169", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle170 {
            get {
                object obj = ResourceManager.GetObject("vehicle170", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle171 {
            get {
                object obj = ResourceManager.GetObject("vehicle171", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle172 {
            get {
                object obj = ResourceManager.GetObject("vehicle172", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle173 {
            get {
                object obj = ResourceManager.GetObject("vehicle173", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle174 {
            get {
                object obj = ResourceManager.GetObject("vehicle174", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle175 {
            get {
                object obj = ResourceManager.GetObject("vehicle175", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle176 {
            get {
                object obj = ResourceManager.GetObject("vehicle176", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle177 {
            get {
                object obj = ResourceManager.GetObject("vehicle177", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle178 {
            get {
                object obj = ResourceManager.GetObject("vehicle178", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle179 {
            get {
                object obj = ResourceManager.GetObject("vehicle179", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle180 {
            get {
                object obj = ResourceManager.GetObject("vehicle180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle181 {
            get {
                object obj = ResourceManager.GetObject("vehicle181", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle182 {
            get {
                object obj = ResourceManager.GetObject("vehicle182", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle183 {
            get {
                object obj = ResourceManager.GetObject("vehicle183", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle184 {
            get {
                object obj = ResourceManager.GetObject("vehicle184", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle185 {
            get {
                object obj = ResourceManager.GetObject("vehicle185", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle186 {
            get {
                object obj = ResourceManager.GetObject("vehicle186", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle187 {
            get {
                object obj = ResourceManager.GetObject("vehicle187", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle188 {
            get {
                object obj = ResourceManager.GetObject("vehicle188", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle189 {
            get {
                object obj = ResourceManager.GetObject("vehicle189", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle190 {
            get {
                object obj = ResourceManager.GetObject("vehicle190", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle191 {
            get {
                object obj = ResourceManager.GetObject("vehicle191", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle192 {
            get {
                object obj = ResourceManager.GetObject("vehicle192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle193 {
            get {
                object obj = ResourceManager.GetObject("vehicle193", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle194 {
            get {
                object obj = ResourceManager.GetObject("vehicle194", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle195 {
            get {
                object obj = ResourceManager.GetObject("vehicle195", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle196 {
            get {
                object obj = ResourceManager.GetObject("vehicle196", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vehicle197 {
            get {
                object obj = ResourceManager.GetObject("vehicle197", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
